function createfigure(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 20-Sep-2015 17:12:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1);

% Create xlabel
xlabel('Day');

% Create ylabel
ylabel('Departure Delay');

% Create title
title('Delays Occuring June 2015');

box(axes1,'on');
