function createfigure(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 20-Sep-2015 16:39:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1,'DisplayName','Days by Departure Delay','Parent',axes1);

% Create xlabel
xlabel('Day');

% Create ylabel
ylabel('Departure Delay');

% Create title
title('Departure Time by Day');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[1 2 3 4 5 6 7]);
