function createfigure(X1, Y1, S1, C1)
%CREATEFIGURE(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 20-Sep-2015 15:51:01

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1);

% Create xlabel
xlabel('Departure Delay');

% Create ylabel
ylabel('Distance Travelled');

% Create title
title('Departure Delay by Distance Travelled');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-200 1600]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 5000]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
